// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRFNl25XN35J-3UGIKDWSE9XM7cbl-Io0',
    appId: '1:309943283601:web:f44d12c54a55dd4960f430',
    messagingSenderId: '309943283601',
    projectId: 'todo-app-98765',
    authDomain: 'todo-app-98765.firebaseapp.com',
    storageBucket: 'todo-app-98765.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT3NGA1HmTFMoyscHWM5ZokotFXwSE2gY',
    appId: '1:309943283601:android:bef4236044aa053760f430',
    messagingSenderId: '309943283601',
    projectId: 'todo-app-98765',
    storageBucket: 'todo-app-98765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0CFylXOj7i_Z4Ivu-pGTm2o_mU68DMaw',
    appId: '1:309943283601:ios:5eb5479256c5ca0360f430',
    messagingSenderId: '309943283601',
    projectId: 'todo-app-98765',
    storageBucket: 'todo-app-98765.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0CFylXOj7i_Z4Ivu-pGTm2o_mU68DMaw',
    appId: '1:309943283601:ios:5eb5479256c5ca0360f430',
    messagingSenderId: '309943283601',
    projectId: 'todo-app-98765',
    storageBucket: 'todo-app-98765.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRFNl25XN35J-3UGIKDWSE9XM7cbl-Io0',
    appId: '1:309943283601:web:be723567fe0248bf60f430',
    messagingSenderId: '309943283601',
    projectId: 'todo-app-98765',
    authDomain: 'todo-app-98765.firebaseapp.com',
    storageBucket: 'todo-app-98765.firebasestorage.app',
  );
}
